const express=require('express');
const multer=require('multer');
const imports=require('../../lib/data-import');
const audit=require('../../lib/audit');
const csrf=require('../../lib/csrf');
const {requireAdmin}=require('../../middleware/auth');
const router=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1},fileFilter:(req,file,cb)=>cb(null,/\.(xlsx|xlsm)$/i.test(file.originalname))});
router.use(requireAdmin);

const branches=()=>require('../../db').db.prepare('SELECT * FROM office_branches WHERE active=1 ORDER BY is_main DESC,name').all();
router.get('/',(req,res)=>{imports.purgeOld();res.render('admin/imports',{definitions:imports.DEFINITIONS,batch:null,error:req.query.error||null,officeBranches:branches()})});
router.get('/template/:entity',async(req,res,next)=>{try{const def=imports.DEFINITIONS[req.params.entity];if(!def)return res.status(404).render('errors/404');const out=await imports.templateBuffer(req.params.entity);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="sanad-${req.params.entity}-template.xlsx"`);res.end(Buffer.from(out))}catch(err){next(err)}});
router.post('/preview',upload.single('file'),csrf.verifyDeferred,async(req,res)=>{const entity=String(req.body.entity||'');try{if(!imports.DEFINITIONS[entity])throw new Error('اختر نوع البيانات');if(!req.file)throw new Error('اختر ملف Excel بصيغة xlsx');const branchId=Number(req.body.office_branch_id),branch=require('../../db').db.prepare('SELECT id FROM office_branches WHERE id=? AND active=1').get(branchId);if(!branch)throw new Error('اختر فرع المكتب الذي تخصه البيانات');const rows=await imports.parseWorkbook(req.file.buffer,entity);const token=imports.saveBatch(req.user.id,entity,req.file.originalname,rows,branch.id);res.redirect(`${req.adminPath}/imports/review/${token}`)}catch(err){res.status(400).render('admin/imports',{definitions:imports.DEFINITIONS,batch:null,error:err.message,officeBranches:branches()})}});
router.get('/review/:token',(req,res)=>{const batch=imports.loadBatch(req.params.token,req.user.id);if(!batch)return res.status(404).render('errors/404');res.render('admin/imports',{definitions:imports.DEFINITIONS,batch,error:null,officeBranches:branches()})});
router.post('/commit/:token',(req,res)=>{const batch=imports.loadBatch(req.params.token,req.user.id);if(!batch)return res.status(404).render('errors/404');try{const outcome=imports.commitBatch(batch,req);if(!outcome.ok){const refreshed=imports.loadBatch(req.params.token,req.user.id);return res.status(409).render('admin/imports',{definitions:imports.DEFINITIONS,batch:refreshed,error:'تغيّرت بيانات النظام بعد المعاينة. راجع الأخطاء الجديدة وأعد رفع الملف.',officeBranches:branches()})}audit.log(req,'data.import',{type:'import',id:batch.id,label:imports.DEFINITIONS[batch.entity].label,details:`استيراد ${outcome.result.count} سجل لفرع ${batch.office_branch_name}`});res.render('admin/imports',{definitions:imports.DEFINITIONS,batch:{...imports.loadBatch(req.params.token,req.user.id),result:outcome.result},error:null,officeBranches:branches()})}catch(err){res.status(400).render('admin/imports',{definitions:imports.DEFINITIONS,batch,error:err.message,officeBranches:branches()})}});
router.use((err,req,res,next)=>{if(err&&err.code==='LIMIT_FILE_SIZE')return res.status(413).render('admin/imports',{definitions:imports.DEFINITIONS,batch:null,error:'حجم الملف أكبر من 5 ميجابايت',officeBranches:branches()});if(err&&err.code==='LIMIT_UNEXPECTED_FILE')return res.status(400).render('admin/imports',{definitions:imports.DEFINITIONS,batch:null,error:'يسمح بملف واحد فقط بصيغة xlsx',officeBranches:branches()});next(err)});
module.exports=router;
