const express = require('express');
const { db } = require('../../db');
const { can } = require('../../middleware/auth');
const audit = require('../../lib/audit');
const reporting = require('../../lib/reporting');
const payrollImport = require('../../lib/payroll-import');
const payrollRollForward = require('../../lib/payroll-roll-forward');
const multer = require('multer');
const csrf = require('../../lib/csrf');

const router = express.Router();
const METHODS = { cash: 'كاش', bank: 'تحويل بنكي', instapay: 'إنستاباي', card: 'شبكة/بطاقة' };
const money = (v) => { v=Number(v); return Number.isFinite(v)&&v>=0&&v<=100000000 ? Math.round(v*100)/100 : 0; };
const period = (v) => /^\d{4}-(0[1-9]|1[0-2])$/.test(String(v||'')) ? v : null;
const clean = (v,n=500) => String(v||'').trim().slice(0,n);
const totals = (b) => {
  const e=['basic_salary','housing_allowance','transport_allowance','fixed_allowance','performance_bonus','exceptional_incentive','overtime_amount','other_earning'];
  const d=['absence_deduction','lateness_deduction','penalty_deduction','advance_deduction','insurance_deduction','tax_deduction','other_deduction'];
  const values={};[...e,...d].forEach(k=>values[k]=money(b[k]));
  values.gross_amount=e.reduce((s,k)=>s+values[k],0);values.total_deductions=d.reduce((s,k)=>s+values[k],0);values.net_amount=Math.max(0,values.gross_amount-values.total_deductions);return values;
};
const treasuryBalance=(id,method)=>Number(db.prepare(`SELECT COALESCE(SUM(CASE WHEN direction='in' THEN amount ELSE -amount END),0) v FROM treasury_transactions WHERE treasury_id=? AND method=? AND voided_at IS NULL AND approval_status='approved'`).get(id,method).v);
const mayEnter=(req)=>req.userCan('payroll.view_own')||req.userCan('payroll.view_all')||req.userCan('payroll.manage')||req.userCan('payroll.approve')||req.userCan('payroll.pay')||req.userCan('payroll.export');
const maySeeAll=(req)=>req.userCan('payroll.view_all')||req.userCan('payroll.manage')||req.userCan('payroll.approve')||req.userCan('payroll.pay')||req.userCan('payroll.export');
const excelUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1},fileFilter:(req,file,cb)=>cb(null,/\.(xlsx|xlsm)$/i.test(file.originalname))});
router.use((req,res,next)=>mayEnter(req)?next():res.status(403).render('admin/denied'));

function runRow(id){return db.prepare(`SELECT r.*,COUNT(i.id) employee_count,COALESCE(SUM(i.gross_amount),0) gross,COALESCE(SUM(i.total_deductions),0) deductions,COALESCE(SUM(i.net_amount),0) net,COALESCE(SUM(i.status='paid'),0) paid_count FROM payroll_runs r LEFT JOIN payroll_items i ON i.payroll_run_id=r.id WHERE r.id=? GROUP BY r.id`).get(id)}
function itemRow(id){return db.prepare(`SELECT i.*,r.period,r.title run_title,r.status run_status,u.email,u.phone,sp.bank_name,sp.iban FROM payroll_items i JOIN payroll_runs r ON r.id=i.payroll_run_id LEFT JOIN users u ON u.id=i.user_id LEFT JOIN salary_profiles sp ON sp.user_id=i.user_id WHERE i.id=?`).get(id)}

router.get('/',(req,res)=>{
  const all=maySeeAll(req);
  const runs=all?db.prepare(`SELECT r.*,COUNT(i.id) employee_count,COALESCE(SUM(i.net_amount),0) net,COALESCE(SUM(i.status='paid'),0) paid_count FROM payroll_runs r LEFT JOIN payroll_items i ON i.payroll_run_id=r.id GROUP BY r.id ORDER BY r.period DESC`).all():[];
  const own=db.prepare(`SELECT i.*,r.period,r.title FROM payroll_items i JOIN payroll_runs r ON r.id=i.payroll_run_id WHERE i.user_id=? AND i.status='paid' ORDER BY r.period DESC`).all(req.user.id);
  const employees=all?db.prepare(`SELECT u.id,u.display_name,u.legal_name,u.job_title,u.national_id,u.active,sp.* FROM users u LEFT JOIN salary_profiles sp ON sp.user_id=u.id WHERE u.active=1 ORDER BY u.display_name`).all():[];
  res.render('admin/payroll',{runs,own,employees,all,METHODS,msg:req.query.msg,err:req.query.err});
});

router.post('/profiles/:userId',can('payroll.manage'),(req,res)=>{
  const uid=Number(req.params.userId),u=db.prepare('SELECT id,display_name FROM users WHERE id=? AND active=1').get(uid);if(!u)return res.sendStatus(404);
  const b=req.body,m=METHODS[b.payment_method]?b.payment_method:'bank';
  db.prepare(`INSERT INTO salary_profiles(user_id,basic_salary,housing_allowance,transport_allowance,fixed_allowance,insurance_default,tax_default,bank_name,iban,payment_method,notes,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET basic_salary=excluded.basic_salary,housing_allowance=excluded.housing_allowance,transport_allowance=excluded.transport_allowance,fixed_allowance=excluded.fixed_allowance,insurance_default=excluded.insurance_default,tax_default=excluded.tax_default,bank_name=excluded.bank_name,iban=excluded.iban,payment_method=excluded.payment_method,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=datetime('now')`).run(uid,money(b.basic_salary),money(b.housing_allowance),money(b.transport_allowance),money(b.fixed_allowance),money(b.insurance_default),money(b.tax_default),clean(b.bank_name,120)||null,clean(b.iban,80)||null,m,clean(b.notes,1000)||null,req.user.id);
  audit.log(req,'payroll.profile',{type:'user',id:uid,label:u.display_name,details:'تحديث تعريف راتب الموظف'});res.redirect(req.adminPath+'/payroll?msg=profile');
});

router.post('/runs',can('payroll.manage'),(req,res)=>{
  const p=period(req.body.period);if(!p)return res.redirect(req.adminPath+'/payroll?err=period');
  if(db.prepare('SELECT 1 FROM payroll_runs WHERE period=?').get(p))return res.redirect(req.adminPath+'/payroll?err=exists');
  const [y,m]=p.split('-').map(Number),last=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10),first=p+'-01';
  const scope=req.body.employee_scope==='specific'?'specific':'all';
  const ids=scope==='specific'?[].concat(req.body.employee_ids||[]).map(Number).filter(Number.isInteger):[];
  if(scope==='specific'&&!ids.length)return res.redirect(req.adminPath+'/payroll?err=scope');
  const users=scope==='specific'
    ?db.prepare(`SELECT u.*,sp.basic_salary,sp.housing_allowance,sp.transport_allowance,sp.fixed_allowance,sp.insurance_default,sp.tax_default FROM users u LEFT JOIN salary_profiles sp ON sp.user_id=u.id WHERE u.active=1 AND u.id IN (${ids.map(()=>'?').join(',')}) ORDER BY u.display_name`).all(...ids)
    :db.prepare(`SELECT u.*,sp.basic_salary,sp.housing_allowance,sp.transport_allowance,sp.fixed_allowance,sp.insurance_default,sp.tax_default FROM users u LEFT JOIN salary_profiles sp ON sp.user_id=u.id WHERE u.active=1 ORDER BY u.display_name`).all();
  const tx=db.transaction(()=>{const r=db.prepare(`INSERT INTO payroll_runs(period,title,notes,created_by,created_by_label) VALUES(?,?,?,?,?)`).run(p,clean(req.body.title,160)||`مرتبات ${p}`,clean(req.body.notes,1000)||null,req.user.id,req.user.display_name),rid=Number(r.lastInsertRowid),add=db.prepare(`INSERT INTO payroll_items(payroll_run_id,user_id,employee_name,job_title,national_id,basic_salary,housing_allowance,transport_allowance,fixed_allowance,performance_bonus,penalty_deduction,insurance_deduction,tax_deduction,gross_amount,total_deductions,net_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);users.forEach(u=>{const review=db.prepare(`SELECT approved_bonus,approved_deduction FROM performance_reviews WHERE user_id=? AND period_from>=? AND period_to<=? AND decision IN ('approved','paid') ORDER BY id DESC LIMIT 1`).get(u.id,first,last)||{},v=totals({basic_salary:u.basic_salary,housing_allowance:u.housing_allowance,transport_allowance:u.transport_allowance,fixed_allowance:u.fixed_allowance,performance_bonus:review.approved_bonus,penalty_deduction:review.approved_deduction,insurance_deduction:u.insurance_default,tax_deduction:u.tax_default});add.run(rid,u.id,u.legal_name||u.display_name,u.job_title||null,u.national_id||null,v.basic_salary,v.housing_allowance,v.transport_allowance,v.fixed_allowance,v.performance_bonus,v.penalty_deduction,v.insurance_deduction,v.tax_deduction,v.gross_amount,v.total_deductions,v.net_amount)});return rid});
  const id=tx();audit.log(req,'payroll.run.create',{type:'payroll',id,label:p,details:`إنشاء سند صرف مرتب ${p}`});res.redirect(`${req.adminPath}/payroll/runs/${id}`);
});

router.get('/runs/:id/template.xlsx',can('payroll.manage'),async(req,res,next)=>{try{const run=runRow(req.params.id);if(!run)return res.sendStatus(404);const out=await payrollImport.template(run.id);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="sanad-payroll-${run.period}.xlsx"`);res.end(Buffer.from(out))}catch(err){next(err)}});
router.post('/runs/:id/import',can('payroll.manage'),(req,res,next)=>excelUpload.single('file')(req,res,err=>{if(err)return res.redirect(`${req.adminPath}/payroll/runs/${req.params.id}?err=excel`);next()}),csrf.verifyDeferred,async(req,res)=>{try{if(!req.file)throw new Error('اختر ملف Excel');const rows=await payrollImport.parse(req.file.buffer,Number(req.params.id));const token=payrollImport.save(req.user.id,Number(req.params.id),req.file.originalname,req.file.buffer,rows);res.redirect(`${req.adminPath}/payroll/imports/${token}`)}catch(err){res.redirect(`${req.adminPath}/payroll/runs/${req.params.id}?err=excel&detail=${encodeURIComponent(err.message)}`)}});
router.get('/imports/:token',can('payroll.manage'),(req,res)=>{const batch=payrollImport.batch(req.params.token,req.user.id);if(!batch)return res.sendStatus(404);res.render('admin/payroll_import',{batch,run:runRow(batch.payroll_run_id),err:req.query.err||''})});
router.post('/imports/:token/apply',can('payroll.manage'),(req,res)=>{try{const run=payrollImport.apply(req.params.token,req.user.id);audit.log(req,'payroll.excel_import',{type:'payroll',id:run.id,label:run.period,details:'استيراد ومراجعة بيانات سند صرف المرتب من Excel'});res.redirect(`${req.adminPath}/payroll/runs/${run.id}?msg=imported`)}catch(err){const batch=payrollImport.batch(req.params.token,req.user.id);if(!batch)return res.redirect(req.adminPath+'/payroll?err=import');res.redirect(`${req.adminPath}/payroll/imports/${req.params.token}?err=${encodeURIComponent(err.message)}`)}});
router.post('/runs/:id/roll-forward',can('payroll.manage'),(req,res)=>{try{const result=payrollRollForward.rollForward(Number(req.params.id),req.body.period,req.user);audit.log(req,'payroll.roll_forward',{type:'payroll',id:result.id,label:result.targetPeriod,details:`ترحيل سند صرف مرتب ${result.source.period} إلى ${result.targetPeriod} دون البنود المتغيرة`});res.redirect(`${req.adminPath}/payroll/runs/${result.id}?msg=rolled`)}catch(err){res.redirect(`${req.adminPath}/payroll?err=${err.message==='exists'?'exists':'period'}`)}});
router.get('/runs/:id',(req,res)=>{if(!maySeeAll(req))return res.status(403).render('admin/denied');const run=runRow(req.params.id);if(!run)return res.sendStatus(404);const items=db.prepare('SELECT * FROM payroll_items WHERE payroll_run_id=? ORDER BY employee_name').all(run.id),treasuries=db.prepare('SELECT * FROM treasuries WHERE active=1 ORDER BY id').all().map(t=>({...t,balances:Object.fromEntries(Object.keys(METHODS).map(m=>[m,treasuryBalance(t.id,m)]))}));res.render('admin/payroll_run',{run,items,treasuries,METHODS,msg:req.query.msg,err:req.query.err,detail:req.query.detail||''})});

router.post('/items/:id',can('payroll.manage'),(req,res)=>{const item=itemRow(req.params.id);if(!item)return res.sendStatus(404);if(item.run_status!=='draft')return res.redirect(`${req.adminPath}/payroll/runs/${item.payroll_run_id}?err=locked`);const v=totals(req.body);db.prepare(`UPDATE payroll_items SET basic_salary=?,housing_allowance=?,transport_allowance=?,fixed_allowance=?,performance_bonus=?,exceptional_incentive=?,overtime_amount=?,other_earning=?,absence_deduction=?,lateness_deduction=?,penalty_deduction=?,advance_deduction=?,insurance_deduction=?,tax_deduction=?,other_deduction=?,earning_note=?,deduction_note=?,gross_amount=?,total_deductions=?,net_amount=?,updated_at=datetime('now') WHERE id=?`).run(v.basic_salary,v.housing_allowance,v.transport_allowance,v.fixed_allowance,v.performance_bonus,v.exceptional_incentive,v.overtime_amount,v.other_earning,v.absence_deduction,v.lateness_deduction,v.penalty_deduction,v.advance_deduction,v.insurance_deduction,v.tax_deduction,v.other_deduction,clean(req.body.earning_note,1000)||null,clean(req.body.deduction_note,1000)||null,v.gross_amount,v.total_deductions,v.net_amount,item.id);audit.log(req,'payroll.item.update',{type:'payroll_item',id:item.id,label:item.employee_name,details:`تعديل راتب ${item.period}`});res.redirect(`${req.adminPath}/payroll/runs/${item.payroll_run_id}?msg=saved`)});

router.post('/runs/:id/approve',can('payroll.approve'),(req,res)=>{const run=runRow(req.params.id);if(!run)return res.sendStatus(404);if(run.status!=='draft')return res.redirect(`${req.adminPath}/payroll/runs/${run.id}?err=locked`);if(run.created_by===req.user.id&&!req.userCan('settings.manage'))return res.redirect(`${req.adminPath}/payroll/runs/${run.id}?err=separation`);db.transaction(()=>{db.prepare("UPDATE payroll_runs SET status='approved',approved_by=?,approved_by_label=?,approved_at=datetime('now'),updated_at=datetime('now') WHERE id=?").run(req.user.id,req.user.display_name,run.id);db.prepare("UPDATE payroll_items SET status='approved' WHERE payroll_run_id=?").run(run.id)})();audit.log(req,'payroll.run.approve',{type:'payroll',id:run.id,label:run.period,details:'اعتماد سند صرف المرتبات'});res.redirect(`${req.adminPath}/payroll/runs/${run.id}?msg=approved`)});

function payItem(req,item,treasuryId,method,reference){if(item.status!=='approved')throw new Error('status');if(!METHODS[method])throw new Error('method');if(treasuryBalance(treasuryId,method)<item.net_amount)throw new Error('balance');const tx=db.prepare(`INSERT INTO treasury_transactions(treasury_id,direction,amount,transaction_date,method,source_name,purpose,reference,payroll_item_id,recorded_by_id,recorded_by,approval_status) VALUES(?,'out',?,date('now'),?,?,?,?,?,?,?,'approved')`).run(treasuryId,item.net_amount,method,item.employee_name,`راتب ${item.period}`,reference||null,item.id,req.user.id,req.user.display_name);db.prepare(`UPDATE payroll_items SET status='paid',treasury_id=?,payment_method=?,payment_reference=?,paid_at=datetime('now'),paid_by=?,paid_by_label=?,updated_at=datetime('now') WHERE id=?`).run(treasuryId,method,reference||`PAY-${tx.lastInsertRowid}`,req.user.id,req.user.display_name,item.id);const left=db.prepare("SELECT COUNT(*) c FROM payroll_items WHERE payroll_run_id=? AND status!='paid'").get(item.payroll_run_id).c;db.prepare("UPDATE payroll_runs SET status=?,updated_at=datetime('now') WHERE id=?").run(left?'partially_paid':'paid',item.payroll_run_id)}
router.post('/items/:id/pay',can('payroll.pay'),(req,res)=>{const item=itemRow(req.params.id);if(!item)return res.sendStatus(404);try{db.transaction(()=>payItem(req,item,Number(req.body.treasury_id),req.body.method,clean(req.body.reference,120)))();audit.log(req,'payroll.item.pay',{type:'payroll_item',id:item.id,label:item.employee_name,details:`صرف راتب ${item.period} بمبلغ ${item.net_amount}`});return res.redirect(`${req.adminPath}/payroll/runs/${item.payroll_run_id}?msg=paid`)}catch(e){return res.redirect(`${req.adminPath}/payroll/runs/${item.payroll_run_id}?err=${e.message}`)}});
router.post('/items/:id/reverse',can('payroll.pay'),(req,res)=>{const item=itemRow(req.params.id);if(!item||item.status!=='paid')return res.sendStatus(404);db.transaction(()=>{db.prepare("UPDATE treasury_transactions SET voided_at=datetime('now'),void_reason=? WHERE payroll_item_id=? AND voided_at IS NULL").run(clean(req.body.reason,300)||'إلغاء صرف راتب',item.id);db.prepare("UPDATE payroll_items SET status='approved',paid_at=NULL,paid_by=NULL,paid_by_label=NULL,payment_reference=NULL,updated_at=datetime('now') WHERE id=?").run(item.id);db.prepare("UPDATE payroll_runs SET status='partially_paid',updated_at=datetime('now') WHERE id=?").run(item.payroll_run_id)})();audit.log(req,'payroll.item.reverse',{type:'payroll_item',id:item.id,label:item.employee_name,details:`إلغاء صرف راتب ${item.period}`});res.redirect(`${req.adminPath}/payroll/runs/${item.payroll_run_id}?msg=reversed`)});

router.get('/items/:id/slip',(req,res)=>{const item=itemRow(req.params.id);if(!item)return res.sendStatus(404);if(!maySeeAll(req)&&item.user_id!==req.user.id)return res.status(403).render('admin/denied');res.render('admin/payroll_slip',{item,METHODS})});
router.get('/runs/:id/export.csv',can('payroll.export'),(req,res)=>{const run=runRow(req.params.id),rows=db.prepare('SELECT * FROM payroll_items WHERE payroll_run_id=? ORDER BY employee_name').all(req.params.id);if(!run)return res.sendStatus(404);reporting.csv(res,`payroll-${run.period}`,['الموظف','الأساسي','بدل السكن','بدل الانتقال','بدلات ثابتة','مكافأة أداء','حافز استثنائي','إضافي','إجمالي الاستحقاقات','غياب','تأخير','جزاءات','سلف','تأمينات','ضرائب','خصومات أخرى','إجمالي الخصومات','الصافي','الحالة'],rows.map(i=>[i.employee_name,i.basic_salary,i.housing_allowance,i.transport_allowance,i.fixed_allowance,i.performance_bonus,i.exceptional_incentive,i.overtime_amount,i.gross_amount,i.absence_deduction,i.lateness_deduction,i.penalty_deduction,i.advance_deduction,i.insurance_deduction,i.tax_deduction,i.other_deduction,i.total_deductions,i.net_amount,i.status]))});
router.get('/runs/:id/print',can('payroll.export'),(req,res)=>{const run=runRow(req.params.id),rows=db.prepare('SELECT * FROM payroll_items WHERE payroll_run_id=? ORDER BY employee_name').all(req.params.id);if(!run)return res.sendStatus(404);reporting.print(res,`كشف مرتبات ${run.period}`,['الموظف','الأساسي','البدلات والحوافز','إجمالي الاستحقاقات','الخصومات','صافي المرتب','الحالة'],rows.map(i=>[i.employee_name,i.basic_salary,i.gross_amount-i.basic_salary,i.gross_amount,i.total_deductions,i.net_amount,i.status==='paid'?'تم الصرف':i.status==='approved'?'معتمد':'مسودة']))});

module.exports=router;
