const express=require('express'),{db}=require('../../db'),{can}=require('../../middleware/auth'),audit=require('../../lib/audit'),reporting=require('../../lib/reporting');
const router=express.Router();router.use(can('performance.view'));
const date=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):null;
function bounds(req){const now=new Date(),from=date(req.query.from)||new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString().slice(0,10),to=date(req.query.to)||new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).toISOString().slice(0,10);return{from,to}}
const dayDiff=(a,b)=>Math.max(0,Math.ceil((new Date(a)-new Date(b))/86400000));
function timing(done,due,paused){if(!done)return 0;const late=Math.max(0,dayDiff(String(done).slice(0,10),due)-paused);return late===0?40:late===1?32:late<=3?24:late<=7?12:0}
function metrics(uid,from,to){
 const today=new Date().toISOString().slice(0,10),cut=to<today?to:today,rows=[];
 db.prepare(`SELECT 'طلب' source,r.id,r.ref label,r.deadline due,r.completed_at completed,r.status,r.reopened_count,r.completion_summary,r.completion_rating,COALESCE((SELECT SUM(julianday(COALESCE(p.resumed_at,datetime('now')))-julianday(p.started_at)) FROM request_time_pauses p WHERE p.request_id=r.id AND p.status IN ('approved','resumed')),0) paused_days,(SELECT COUNT(*) FROM todos WHERE request_id=r.id) todo_total,(SELECT COUNT(*) FROM todos WHERE request_id=r.id AND done=1) todo_done,(SELECT COUNT(*) FROM documents WHERE request_id=r.id) docs,COALESCE((SELECT contribution_percent FROM request_assignee_shares s WHERE s.request_id=r.id AND s.user_id=?),100.0/(SELECT COUNT(*) FROM request_assignees z WHERE z.request_id=r.id)) contribution FROM requests r JOIN request_assignees a ON a.request_id=r.id WHERE a.user_id=? AND r.archived_at IS NULL AND r.deadline BETWEEN ? AND ? AND r.deadline<=? AND (r.status!='completed' OR r.completed_at IS NOT NULL)`).all(uid,uid,from,to,cut).forEach(x=>{const done=x.status==='completed'||!!x.completed,lateDays=done?Math.max(0,dayDiff(String(x.completed).slice(0,10),x.due)-Math.floor(x.paused_days)):0,time=timing(x.completed,x.due,Math.floor(x.paused_days)),steps=x.todo_total?25*(x.todo_done/x.todo_total):(done?25:0),quality=x.reopened_count===0?20:x.reopened_count===1?10:0,documentation=x.docs&&x.completion_summary?10:0,rating=done?Math.max(0,Math.min(5,Number(x.completion_rating)||0)):0,score=Math.round((time+steps+quality+documentation+rating)*10)/10;rows.push({...x,done,lateDays,score,weight:(Number(x.contribution)||100)/100})});
 db.prepare(`SELECT 'قضية' source,t.title label,t.due_on due,t.completed_at completed,t.status FROM case_tasks t WHERE t.assigned_user_id=? AND t.due_on BETWEEN ? AND ? AND t.due_on<=?`).all(uid,from,to,cut).forEach(x=>{const done=x.status==='completed'||!!x.completed;rows.push({...x,done,lateDays:done?dayDiff(String(x.completed).slice(0,10),x.due):0,score:timing(x.completed,x.due,0)*2.5,weight:1})});
 db.prepare(`SELECT 'أجندة' source,e.title label,substr(COALESCE(e.ends_at,e.starts_at),1,10) due,e.completed_at completed,e.status FROM agenda_events e JOIN agenda_assignees a ON a.agenda_event_id=e.id WHERE a.user_id=? AND substr(COALESCE(e.ends_at,e.starts_at),1,10) BETWEEN ? AND ? AND substr(COALESCE(e.ends_at,e.starts_at),1,10)<=?`).all(uid,from,to,cut).forEach(x=>{const done=x.status==='completed'||!!x.completed;rows.push({...x,done,lateDays:done?dayDiff(String(x.completed).slice(0,10),x.due):0,score:timing(x.completed,x.due,0)*2.5,weight:1})});
 let completed=0,onTime=0,late=0,overdue=0,paused=0,reopened=0,totalDays=0,totalWeight=0,weighted=0;rows.forEach(x=>{if(x.done){completed++;totalDays+=x.lateDays;if(x.lateDays===0)onTime++;else late++}else if(x.due<today)overdue++;if(x.paused_days>0)paused++;reopened+=Number(x.reopened_count)||0;weighted+=x.score*x.weight;totalWeight+=x.weight});const electronicScore=totalWeight?Math.round(weighted/totalWeight*10)/10:0;return{assigned:rows.length,completed,onTime,late,overdue,paused,reopened,avgDays:completed?Math.round(totalDays/completed*10)/10:0,electronicScore,rows}}
function load(req){const {from,to}=bounds(req),staff=db.prepare("SELECT id,display_name,job_title,role FROM users WHERE active=1 AND role!='admin' ORDER BY display_name").all();const result=staff.map(u=>{const m=metrics(u.id,from,to),rule=db.prepare('SELECT * FROM performance_rules WHERE user_id=?').get(u.id)||{target_percent:90,bonus_amount:0,deduction_per_overdue:0,notes:''},review=db.prepare('SELECT * FROM performance_reviews WHERE user_id=? AND period_from=? AND period_to=?').get(u.id,from,to),adminScore=Number(review?.administrative_score)||0,finalScore=Math.round((m.electronicScore*.8+adminScore)*10)/10;return{...u,...m,rule,review,adminScore,finalScore,recommendedBonus:m.assigned&&finalScore>=rule.target_percent?rule.bonus_amount:0,recommendedDeduction:m.overdue*rule.deduction_per_overdue}});return{from,to,staff:result}}
router.get('/',(req,res)=>res.render('admin/performance',{...load(req),msg:req.query.msg}));
router.post('/:userId/rule',can('performance.manage'),(req,res)=>{const uid=Number(req.params.userId),target=Math.max(0,Math.min(100,Number(req.body.target_percent)||0)),bonus=Math.max(0,Number(req.body.bonus_amount)||0),deduction=Math.max(0,Number(req.body.deduction_per_overdue)||0);db.prepare(`INSERT INTO performance_rules(user_id,target_percent,bonus_amount,deduction_per_overdue,notes,updated_by) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET target_percent=excluded.target_percent,bonus_amount=excluded.bonus_amount,deduction_per_overdue=excluded.deduction_per_overdue,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=datetime('now')`).run(uid,target,bonus,deduction,String(req.body.notes||'').trim()||null,req.user.id);res.redirect(`${req.adminPath}/performance?from=${req.body.from}&to=${req.body.to}&msg=rule`)});
router.post('/:userId/review',can('performance.manage'),(req,res)=>{const uid=Number(req.params.userId),from=date(req.body.from),to=date(req.body.to);if(!from||!to)return res.redirect(req.adminPath+'/performance');const m=metrics(uid,from,to),admin=Math.max(0,Math.min(20,Number(req.body.administrative_score)||0)),score=Math.round((m.electronicScore*.8+admin)*10)/10,rule=db.prepare('SELECT * FROM performance_rules WHERE user_id=?').get(uid)||{target_percent:90,bonus_amount:0,deduction_per_overdue:0},recBonus=m.assigned&&score>=rule.target_percent?rule.bonus_amount:0,recDeduction=m.overdue*rule.deduction_per_overdue,bonus=Math.max(0,Number(req.body.approved_bonus)||0),deduction=Math.max(0,Number(req.body.approved_deduction)||0),decision=['approved','paid','cancelled'].includes(req.body.decision)?req.body.decision:'pending',paid=decision==='paid'?new Date().toISOString().slice(0,19).replace('T',' '):null;db.prepare(`INSERT INTO performance_reviews(user_id,period_from,period_to,assigned_count,completed_count,on_time_count,late_count,overdue_count,score,electronic_score,administrative_score,recommended_bonus,recommended_deduction,approved_bonus,approved_deduction,decision,notes,reviewed_by,reviewed_by_label,paid_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,period_from,period_to) DO UPDATE SET assigned_count=excluded.assigned_count,completed_count=excluded.completed_count,on_time_count=excluded.on_time_count,late_count=excluded.late_count,overdue_count=excluded.overdue_count,score=excluded.score,electronic_score=excluded.electronic_score,administrative_score=excluded.administrative_score,recommended_bonus=excluded.recommended_bonus,recommended_deduction=excluded.recommended_deduction,approved_bonus=excluded.approved_bonus,approved_deduction=excluded.approved_deduction,decision=excluded.decision,notes=excluded.notes,reviewed_by=excluded.reviewed_by,reviewed_by_label=excluded.reviewed_by_label,paid_at=excluded.paid_at,updated_at=datetime('now')`).run(uid,from,to,m.assigned,m.completed,m.onTime,m.late,m.overdue,score,m.electronicScore,admin,recBonus,recDeduction,bonus,deduction,decision,String(req.body.notes||'').trim()||null,req.user.id,req.user.display_name,paid);audit.log(req,'performance.review',{type:'user',id:uid,label:'تقييم موظف',details:`إلكتروني ${m.electronicScore}%، إداري ${admin}/20، نهائي ${score}%`});res.redirect(`${req.adminPath}/performance?from=${from}&to=${to}&msg=review`)});
router.get('/export.csv',can('performance.export'),(req,res)=>{const x=load(req);reporting.csv(res,'sanad-performance',['الموظف','المطلوب','المنجز','في الموعد','بعد الموعد','متأخر','متوقف','معاد فتحه','متوسط التأخير','الإلكتروني','الإداري','النهائي','المكافأة','الخصم'],x.staff.map(u=>[u.display_name,u.assigned,u.completed,u.onTime,u.late,u.overdue,u.paused,u.reopened,u.avgDays,u.electronicScore,u.adminScore,u.finalScore,u.review?.approved_bonus||0,u.review?.approved_deduction||0]))});
router.get('/print',can('performance.export'),(req,res)=>{const x=load(req);reporting.print(res,`تقييم الموظفين من ${x.from} إلى ${x.to}`,['الموظف','المطلوب','المنجز','في الموعد','متأخر','متوقف','الإلكتروني','الإداري','النهائي'],x.staff.map(u=>[u.display_name,u.assigned,u.completed,u.onTime,u.overdue,u.paused,u.electronicScore+'%',u.adminScore+'/20',u.finalScore+'%']))});
module.exports=router;
