const express=require('express'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const {db}=require('../../db'),audit=require('../../lib/audit'),{can}=require('../../middleware/auth'),reporting=require('../../lib/reporting'),csrf=require('../../lib/csrf');
const router=express.Router();router.use(can('treasury.view'));
const dir=path.join(process.env.DATA_DIR||path.join(__dirname,'..','..','data'),'treasury');fs.mkdirSync(dir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:dir,filename:(_r,f,cb)=>cb(null,crypto.randomBytes(16).toString('hex')+path.extname(f.originalname).toLowerCase())}),limits:{fileSize:8*1024*1024},fileFilter:(_r,f,cb)=>cb(null,/^(image\/(jpeg|png|webp)|application\/pdf)$/.test(f.mimetype))});
const methods={cash:'كاش',bank:'تحويل بنكي',instapay:'إنستاباي',card:'شبكة/بطاقة',other:'أخرى',custody:'عهدة'};
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?v:null,amount=v=>{v=Number(v);return Number.isFinite(v)&&v>0&&v<=100000000?Math.round(v*100)/100:null},clean=(v,n=500)=>String(v||'').trim().slice(0,n);
function balance(tid,method=''){const w=["voided_at IS NULL","approval_status='approved'",'treasury_id=?'],p=[tid];if(method){w.push('method=?');p.push(method)}return Number(db.prepare(`SELECT COALESCE(SUM(CASE WHEN direction='in' THEN amount ELSE -amount END),0) v FROM treasury_transactions WHERE ${w.join(' AND ')}`).get(...p).v)}
/*
 * Totals used to be summed in JavaScript over the 1000 displayed rows only —
 * correct while a filtered period stayed under that many transactions, silently
 * wrong (undercounted, with no indication) the moment it did not. They are now
 * summed by SQL over every matching row, independent of how many are shown.
 */
function data(req,limit=1000){const treasuries=db.prepare('SELECT * FROM treasuries WHERE active=1 ORDER BY id').all().map(t=>({...t,balance:balance(t.id),byMethod:Object.fromEntries(Object.keys(methods).map(m=>[m,balance(t.id,m)]))}));const where=['x.voided_at IS NULL'],p=[];if(req?.query.method&&methods[req.query.method]){where.push('x.method=?');p.push(req.query.method)}if(req?.query.direction&&['in','out'].includes(req.query.direction)){where.push('x.direction=?');p.push(req.query.direction)}if(validDate(req?.query.from)){where.push('x.transaction_date>=?');p.push(req.query.from)}if(validDate(req?.query.to)){where.push('x.transaction_date<=?');p.push(req.query.to)}const whereSql=where.join(' AND ');const rows=db.prepare(`SELECT x.*,t.name treasury_name,u.display_name employee_name,r.ref request_ref,c.full_name client_name FROM treasury_transactions x JOIN treasuries t ON t.id=x.treasury_id LEFT JOIN staff_custodies sc ON sc.id=x.custody_id LEFT JOIN users u ON u.id=sc.user_id LEFT JOIN requests r ON r.id=x.request_id LEFT JOIN clients c ON c.id=x.client_id WHERE ${whereSql} ORDER BY x.transaction_date DESC,x.id DESC ${limit>0?'LIMIT '+Math.max(1,Math.min(Number(limit)||1000,100000)):''}`).all(...p);const totalsRow=db.prepare(`SELECT COALESCE(SUM(CASE WHEN x.approval_status='approved' AND x.direction='in' THEN x.amount ELSE 0 END),0) incoming,COALESCE(SUM(CASE WHEN x.approval_status='approved' AND x.direction='out' THEN x.amount ELSE 0 END),0) outgoing,COUNT(*) matched FROM treasury_transactions x WHERE ${whereSql}`).get(...p);const totals={incoming:totalsRow.incoming,outgoing:totalsRow.outgoing};return{treasuries,rows,totals,methods,rowsTruncated:totalsRow.matched>rows.length}}
router.get('/',(req,res)=>res.render('admin/treasury',{...data(req),filters:req.query,msg:req.query.msg,err:req.query.err,clients:db.prepare('SELECT id,full_name FROM clients ORDER BY full_name LIMIT 500').all(),requests:db.prepare('SELECT id,ref,name FROM requests WHERE archived_at IS NULL ORDER BY id DESC LIMIT 500').all()}));
function splits(b){const ms=[].concat(b.method||[]),as=[].concat(b.split_amount||[]),out=[];ms.forEach((m,i)=>{const a=amount(as[i]);if(methods[m]&&a)out.push([m,a,i])});return out}
router.post('/deposit',can('treasury.manage'),upload.single('attachment'),csrf.verifyDeferred,(req,res)=>{const b=req.body,d=validDate(b.transaction_date),tid=Number(b.treasury_id),t=db.prepare('SELECT * FROM treasuries WHERE id=? AND active=1').get(tid),parts=splits(b);if(!parts.length||!d||!t)return res.redirect(req.adminPath+'/treasury?err=invalid');const group=crypto.randomBytes(8).toString('hex'),add=db.prepare(`INSERT INTO treasury_transactions(treasury_id,direction,amount,transaction_date,transaction_time,method,source_name,purpose,reference,recorded_by_id,recorded_by,group_ref,client_id,request_id,bank_name,account_no,recipient_name,notes,attachment_path) VALUES(?,'in',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);db.transaction(()=>parts.forEach(([method,a,i])=>add.run(tid,a,d,clean(b.transaction_time,5)||null,method,clean(b.source_name)||'مدير الشركة',clean(b.purpose)||'وارد خزنة',clean([].concat(b.reference||[])[i]||b.reference)||null,req.user.id,req.user.display_name,group,Number(b.client_id)||null,Number(b.request_id)||null,clean([].concat(b.bank_name||[])[i])||null,clean([].concat(b.account_no||[])[i])||null,clean([].concat(b.recipient_name||[])[i])||null,clean(b.notes,1000)||null,req.file?req.file.filename:null)))();audit.log(req,'treasury.deposit',{type:'treasury',id:tid,label:t.name,details:`وارد ${parts.reduce((s,x)=>s+x[1],0)} عبر ${parts.length} طريقة`});res.redirect(req.adminPath+'/treasury?msg=deposited')});
router.post('/withdraw',can('treasury.manage'),upload.single('attachment'),csrf.verifyDeferred,(req,res)=>{const b=req.body,d=validDate(b.transaction_date),tid=Number(b.treasury_id),m=methods[b.method]?b.method:null,a=amount(b.amount);if(!d||!tid||!m||!a)return res.redirect(req.adminPath+'/treasury?err=invalid');if(balance(tid,m)<a)return res.redirect(req.adminPath+'/treasury?err=insufficient');const status=req.userCan('settings.manage')?'approved':'pending';const info=db.prepare(`INSERT INTO treasury_transactions(treasury_id,direction,amount,transaction_date,transaction_time,method,source_name,purpose,reference,recorded_by_id,recorded_by,notes,attachment_path,approval_status) VALUES(?,'out',?,?,?,?,?,?,?,?,?,?,?,?)`).run(tid,a,d,clean(b.transaction_time,5)||null,m,clean(b.beneficiary),clean(b.purpose)||'منصرف خزنة',clean(b.reference)||null,req.user.id,req.user.display_name,clean(b.notes,1000)||null,req.file?req.file.filename:null,status);audit.log(req,'treasury.withdraw',{type:'treasury_transaction',id:Number(info.lastInsertRowid),label:clean(b.purpose)||'منصرف خزنة',details:`${a} — ${status}`});res.redirect(req.adminPath+`/treasury?msg=${status==='approved'?'withdrawn':'pending'}`)});

router.post('/:id/approve',can('settings.manage'),(req,res)=>{const row=db.prepare("SELECT * FROM treasury_transactions WHERE id=? AND direction='out' AND approval_status='pending' AND voided_at IS NULL").get(Number(req.params.id));if(!row)return res.redirect(req.adminPath+'/treasury?err=not_pending');if(balance(row.treasury_id,row.method)<Number(row.amount))return res.redirect(req.adminPath+'/treasury?err=insufficient');db.prepare("UPDATE treasury_transactions SET approval_status='approved' WHERE id=?").run(row.id);audit.log(req,'treasury.approve',{type:'treasury_transaction',id:row.id,label:row.purpose||String(row.id),details:String(row.amount)});res.redirect(req.adminPath+'/treasury?msg=approved')});
router.post('/:id/reject',can('settings.manage'),(req,res)=>{const row=db.prepare("SELECT * FROM treasury_transactions WHERE id=? AND direction='out' AND approval_status='pending' AND voided_at IS NULL").get(Number(req.params.id));if(!row)return res.redirect(req.adminPath+'/treasury?err=not_pending');db.prepare("UPDATE treasury_transactions SET approval_status='rejected',voided_at=datetime('now'),void_reason=? WHERE id=?").run(clean(req.body.reason)||'رفض الصرف',row.id);audit.log(req,'treasury.reject',{type:'treasury_transaction',id:row.id,label:row.purpose||String(row.id),details:String(row.amount)});res.redirect(req.adminPath+'/treasury?msg=rejected')});
router.post('/transfer',can('treasury.manage'),(req,res)=>{const from=Number(req.body.from_treasury_id),to=Number(req.body.to_treasury_id),m=methods[req.body.method]?req.body.method:null,a=amount(req.body.amount),d=validDate(req.body.transaction_date);if(!from||!to||from===to||!m||!a||!d||balance(from,m)<a)return res.redirect(req.adminPath+'/treasury?err=invalid');const g=crypto.randomBytes(8).toString('hex'),q=db.prepare(`INSERT INTO treasury_transactions(treasury_id,direction,amount,transaction_date,method,source_name,purpose,group_ref,recorded_by_id,recorded_by) VALUES(?,?,?,?,?,?,?,?,?,?)`);db.transaction(()=>{q.run(from,'out',a,d,m,'تحويل داخلي','تحويل إلى خزنة أخرى',g,req.user.id,req.user.display_name);q.run(to,'in',a,d,m,'تحويل داخلي','تحويل من خزنة أخرى',g,req.user.id,req.user.display_name)})();res.redirect(req.adminPath+'/treasury?msg=transferred')});
router.post('/:id/void',can('treasury.manage'),(req,res)=>{db.prepare("UPDATE treasury_transactions SET voided_at=datetime('now'),void_reason=? WHERE id=? AND voided_at IS NULL").run(clean(req.body.reason)||'إلغاء الحركة',req.params.id);res.redirect(req.adminPath+'/treasury?msg=voided')});
router.get('/export.csv',can('treasury.export'),(req,res)=>{const x=data(req,0);reporting.csv(res,'sanad-treasury',['رقم الحركة','التاريخ','الوقت','الخزنة','الحركة','المبلغ','الطريقة','المصدر/المستفيد','الطلب','الموظف','الحالة'],x.rows.map(r=>[r.id,r.transaction_date,r.transaction_time,r.treasury_name,r.direction==='in'?'وارد':'منصرف',r.amount,methods[r.method]||r.method,r.employee_name||r.source_name,r.request_ref,r.recorded_by,r.approval_status]))});
router.get('/print',can('treasury.export'),(req,res)=>{const x=data(req,0);reporting.print(res,'تقرير حركة الخزنة',['التاريخ','الخزنة','الحركة','المبلغ','الطريقة','المصدر/المستفيد','الطلب'],x.rows.map(r=>[r.transaction_date,r.treasury_name,r.direction==='in'?'وارد':'منصرف',r.amount,methods[r.method]||r.method,r.employee_name||r.source_name,r.request_ref||'—']))});
module.exports=router;
